### ISSUE TITLE
[2016] Summer Olympics, Brazil.

### ISSUE THREAD

**Issue by alloy** [alloy/life#1]
From 05-08 till 21-08.
- http://www.rio2016.com/en
- http://www.olympic.org/rio-2016-summer-olympics
### TODOs
- [ ] Get tickets. Not much is known yet about when they will be available: http://www.rio2016.com/en/how-can-i-buy-admission-tickets
- [ ] Investigate how to get the most affordable long term location to stay. I.e. rent apartment.
- [ ] Investigate when to best buy flight tickets.
### Sports we’d like to see
- Athletics
- Gymnastics
- Swimming
- Football
- Judo
- Hockey
- Canoe/kayak
- Rowing
- Cycling
- Volleyball

**Comment by alloy** [comment]
List of sports according to the official newsletter:

![screen shot 2014-02-20 at 10 47 13](https://f.cloud.github.com/assets/2320/2216965/27ed5ae8-9a14-11e3-9213-c812a8fa0266.png)

**Comment by floere** [comment]
- [ ] Say hi to @floere there, if he can manage to make it.

**Comment by alloy** [comment]
@floere Do you have any concrete plans and/or any tips of what to keep in mind?
